Booky Store/Controllers/RetrieveController.cs
using Booky_Store.Data;
using Booky_Store.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Security.Claims;
using System.Security.Principal;
using Volo.Abp.Users;

namespace Booky_Store.Controllers
{
    public class RetrieveController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RetrieveController(ApplicationDbContext context,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            IEnumerable<Book> AllBooks=_context.books.Include(m=>m.ApplicationUser).ToList();
            return View(AllBooks);
        }
        public IActionResult Add()
        {
            //To get Current user Id
            var claimsIdentity = (ClaimsIdentity)User.Identity;

            var user = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (user == null) return NotFound("No user Logged in");

            var userId = user.Value;
            //To get current user usind Id
            ApplicationUser MyUser = _context.Users.Find(userId);
            if (MyUser == null) return NotFound("No User found");

            ApplicationUserBook CurrUser=new ApplicationUserBook();
            CurrUser.ApplicationUser = new ApplicationUser
            {
                UserName=MyUser.UserName,
                Email=MyUser.Email,
                FirstName=MyUser.FirstName,
                LastName=MyUser.LastName,
                PhoneNumber=MyUser.PhoneNumber,
            };

            return View(CurrUser);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(ApplicationUserBook AddedBook)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;

            var user = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (user == null) return NotFound("No user Logged in");

            var userId = user.Value;
            ApplicationUser MyUser = _context.Users.Find(userId);
            if (MyUser == null) return NotFound("No User found");
            

            Book book;
            book = new Book
            {
                ApplicationUser=MyUser,
                AuthorName=AddedBook.Book.AuthorName,
                BookImage=AddedBook.Book.BookImage,
                Name=AddedBook.Book.Name,
            };
            if (Request.Form.Files.Count > 0)
            {
                var file = Request.Form.Files.FirstOrDefault();
                using (var datastream = new MemoryStream())
                {
                    await file.CopyToAsync(datastream);
                    book.BookImage=datastream.ToArray();
                }
            }
            if(book.Name is null || book.AuthorName is null || book.BookImage is null)
            {
                return BadRequest("Wrong input");
            }
            _context.books.Add(book);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        public  IActionResult BookDetails(int id)
        {
            Book RetrivedBook =  _context.books.Include(m=>m.ApplicationUser).FirstOrDefault(x=>x.Id==id);

            if (RetrivedBook == null) return NotFound();
            return View(RetrivedBook);
        }
        public IActionResult RemoveBook(int id)
        {
            var book = _context.books.FirstOrDefault(x=>x.Id==id);
            if(book==null) return NotFound();

            _context.books.Remove(book);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Booky Store/Views/Retrieve/Add.cshtml
@model ApplicationUserBook

@{
	ViewData["title"] = "Add Book";
}

<form asp-action="Add" method="post" enctype="multipart/form-data">
	<label asp-for="@Model.Book.Name"></label>
	<input asp-for="@Model.Book.Name" />
	<span asp-validation-for="@Model.Book.Name" class="text-danger"></span>
	<br />
	<label asp-for="@Model.Book.AuthorName"></label>
	<input asp-for="@Model.Book.AuthorName" />
	<span asp-validation-for="@Model.Book.AuthorName" class="text-danger"></span>
	<br />
	<label asp-for="@Model.ApplicationUser.UserName"></label>
	<input asp-for="@Model.ApplicationUser.UserName" value="@Model.ApplicationUser.UserName" disabled />
	<span asp-validation-for="@Model.ApplicationUser.UserName" class="text-danger"></span>
	<br />
	<label asp-for="@Model.ApplicationUser.PhoneNumber"></label>
	<input asp-for="@Model.ApplicationUser.PhoneNumber" value="@Model.ApplicationUser.PhoneNumber" disabled />
	<span asp-validation-for="@Model.ApplicationUser.PhoneNumber" class="text-danger"></span>
	<br />

	<div>
		<label asp-for="@Model.Book.BookImage"></label>
		<input type="file" asp-for="@Model.Book.BookImage" />

		@*@if(Model.Book.BookImage is null){
			<h1>No image</h1>
		}
		else{
			<img alt="book image" src="data:image/*;base64,@(Convert.ToBase64String(Model.Book.BookImage))" />
		}*@

	</div>

	<br />
	<button type="submit" class="btn btn-primary">Add</button>

</form>

Booky Store/Views/Retrieve/BookDetails.cshtml
@model Book

@{
	ViewData["title"] = "Details";
}


<div>
	<label>
		<img src="data:image/*;base64,@(Convert.ToBase64String(Model.BookImage))" alt="Book Image" width="400" height="400"/><br />
		Book Name: @Model.Name <br />
		Author Name: @Model.AuthorName<br />

		Seller: @Model.ApplicationUser.FirstName
		@Model.ApplicationUser.LastName<br />
		Contact Information:<br />
		&nbsp;&nbsp;&nbsp;&nbsp;@Model.ApplicationUser.Email <br />
		&nbsp;&nbsp;&nbsp;&nbsp; @Model.ApplicationUser.PhoneNumber<br />
		
		<a asp-controller="Retrieve" asp-action="Index" class="btn btn-primary">Back</a>
		
		@if(User.IsInRole("Admin")){
			<a asp-controller="Retrieve" asp-action="RemoveBook" asp-route-id="@Model.Id" class="btn btn-secondary">Remove</a>
		}
	</label>
</div>

Booky Store/Views/Retrieve/Index.cshtml
@model IEnumerable<Book>

@{
    ViewData["title"] = "Find a book";
}

<h1>
    Find a book
</h1>
@if (User.Identity.IsAuthenticated)
{
<a class="btn btn-primary" asp-action="Add">
    Add your book
</a>
}
else{
    <h3>You must login to offer your books</h3>
}

<table class="table">
    <tbody>
        @foreach(var x in Model){
            <tr>
                <div>
                <td>
                    <div>
                        <a href="https://www.google.com"> 
                            <img src="data:image/*;base64,@(Convert.ToBase64String(x.BookImage))" alt="" width="200" height="200">
                         </a>
                    </div>
                    Book Name: @x.Name<br>
                    Seller Name: @x.ApplicationUser.UserName<br>
                    Contact: @x.ApplicationUser.PhoneNumber
                    <br>
                    <a asp-controller="Retrieve" asp-action="BookDetails" asp-route-id="@x.Id" class="btn btn-primary">Details</a>
                </td>
                </div>
            </tr>
        }
    </tbody>
</table>




@*@for(int i=0;i<10;i++){
            <tr>
                @for(int j=0;j<3;j++){
                    <div>
                    <td>
                        <div>
                            <a href="https://www.google.com"><img src="~/css/book1.jpg"></a>
                        </div>
                        Book Name<br>
                        Book Seller<br>
                        <button class="btn btn-primary">Details</button>
                    </td>
                    </div>
                }
            </tr>
        }*@